# Generated by Django 4.2.6 on 2023-10-20 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("english", models.PositiveSmallIntegerField()),
                ("math", models.PositiveSmallIntegerField()),
                ("science", models.PositiveSmallIntegerField()),
                ("exam_date", models.DateTimeField()),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="study.students"
                    ),
                ),
            ],
        ),
    ]
