# Generated by Django 4.2.6 on 2023-10-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0002_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="exam_date",
            field=models.DateTimeField(null=True),
        ),
    ]
